export type LandingLanguage = "rw" | "en" | "fr";

const french: Record<string, string> = {
  "Home": "Accueil",
  "Features": "Fonctionnalités",
  "How it works": "Fonctionnement",
  "About us": "À propos",
  "Contact us": "Nous contacter",
  "Dashboard": "Tableau de bord",
  "Log out": "Se déconnecter",
  "Log in": "Se connecter",
  "Sign up": "S’inscrire",
  "New": "Nouveau",
  "Trusted by Modern Sellers": "Adopté par les vendeurs modernes",
  "One clear place to run": "Un seul espace clair pour gérer",
  "your whole business.": "toute votre entreprise.",
  "Kungahara brings your stock, sales, finances, and documents into one calm workspace—so you spend less time chasing numbers and more time growing.": "Kungahara réunit votre stock, vos ventes, vos finances et vos documents dans un espace simple, afin que vous consacriez moins de temps aux chiffres et davantage à votre croissance.",
  "Open dashboard": "Ouvrir le tableau de bord",
  "Get started free": "Commencer gratuitement",
  "Continue to workplace": "Accéder à l’espace de travail",
  "Kungahara dashboard preview": "Aperçu du tableau de bord Kungahara",
  "Kungahara dashboard showing finances, stock, sales, and business insights": "Tableau de bord Kungahara présentant les finances, le stock, les ventes et les indicateurs de l’entreprise",
  "Run the business.": "Gérez votre entreprise.",
  "See the whole picture.": "Gardez une vue d’ensemble.",
  "Each tool is useful on its own. Together, they give you one dependable view of how your business is doing.": "Chaque outil est utile séparément. Ensemble, ils vous offrent une vue fiable de la situation de votre entreprise.",
  "A dashboard that makes sense": "Un tableau de bord facile à comprendre",
  "See income, expenses, profit, stock value, and business activity without digging through separate tools.": "Consultez les revenus, les dépenses, les bénéfices, la valeur du stock et l’activité sans parcourir plusieurs outils.",
  "Stock you can trust": "Un stock fiable",
  "Know what is available, what is selling, and which products need your attention before they run out.": "Sachez ce qui est disponible, ce qui se vend et quels produits nécessitent votre attention avant la rupture de stock.",
  "Sales, clearly recorded": "Des ventes clairement enregistrées",
  "Record sales quickly and understand which products, periods, and categories are driving your revenue.": "Enregistrez rapidement les ventes et identifiez les produits, périodes et catégories qui génèrent vos revenus.",
  "Finance without the guesswork": "Des finances sans incertitude",
  "Follow money invested, income, profit, losses, and loan deadlines from one organized workspace.": "Suivez l’argent investi, les revenus, les bénéfices, les pertes et les échéances de prêts depuis un espace organisé.",
  "Documents kept close": "Vos documents à portée de main",
  "Store receipts, agreements, invoices, and business records in folders that are easy to find later.": "Conservez reçus, contrats, factures et dossiers professionnels dans des dossiers faciles à retrouver.",
  "Built around your currency": "Conçu pour votre devise",
  "Work naturally in RWF and monitor additional currencies without losing sight of your real business totals.": "Travaillez naturellement en RWF et suivez d’autres devises sans perdre de vue les totaux réels de votre entreprise.",
  "Learn more": "En savoir plus",
  "From scattered details": "Des informations dispersées",
  "to confident decisions.": "aux décisions éclairées.",
  "Kungahara keeps the process simple. Add what happens in your business, and your workspace turns it into a clear, useful picture.": "Kungahara simplifie le processus. Ajoutez les activités de votre entreprise et votre espace les transforme en une vue claire et utile.",
  "Start your workspace": "Créer votre espace",
  "Create your workspace": "Créez votre espace",
  "Start with a secure account and set up the business information that matters to you.": "Commencez avec un compte sécurisé et configurez les informations essentielles de votre entreprise.",
  "Add your daily activity": "Ajoutez vos activités quotidiennes",
  "Record products, sales, documents, expenses, and loans as your business moves.": "Enregistrez les produits, ventes, documents, dépenses et prêts au fil de votre activité.",
  "Make clearer decisions": "Prenez des décisions plus claires",
  "Use live summaries and trends to know what is working and what needs attention next.": "Utilisez les résumés et tendances en direct pour savoir ce qui fonctionne et ce qui demande votre attention.",
  "Built for the way growing businesses really work.": "Conçu pour le fonctionnement réel des entreprises en croissance.",
  "Clarity for every business day.": "De la clarté au quotidien.",
  "connected workspaces": "espaces connectés",
  "Designed with simplicity at the center.": "Conçu autour de la simplicité.",
  "About Kungahara": "À propos de Kungahara",
  "Business software": "Un logiciel de gestion",
  "should feel human.": "qui reste humain.",
  "Kungahara exists to make everyday business management easier to understand. We bring essential tools together in a focused experience shaped around clarity, confidence, and steady growth.": "Kungahara rend la gestion quotidienne plus facile à comprendre. Nous réunissons les outils essentiels dans une expérience claire, rassurante et pensée pour une croissance régulière.",
  "From a first sale to a growing product catalogue, the workspace helps business owners stay close to the details without becoming overwhelmed by them.": "De la première vente à un catalogue en pleine croissance, l’espace aide les entrepreneurs à suivre les détails sans se sentir dépassés.",
  "Talk to our team": "Parler à notre équipe",
  "Everything you need": "Tout ce dont vous avez besoin",
  "to get started.": "pour bien commencer.",
  "Who is Kungahara designed for?": "À qui Kungahara est-il destiné ?",
  "Kungahara is designed for growing shops, sellers, and small businesses that want a clearer way to manage stock, sales, finances, and records.": "Kungahara est conçu pour les boutiques, vendeurs et petites entreprises en croissance qui souhaitent gérer plus clairement leur stock, leurs ventes, leurs finances et leurs dossiers.",
  "Do I need accounting experience?": "Dois-je avoir des connaissances en comptabilité ?",
  "No. The workspace uses straightforward language and visual summaries so you can understand the health of your business without specialist software knowledge.": "Non. L’espace utilise un langage simple et des résumés visuels pour vous aider à comprendre la santé de votre entreprise sans connaissances spécialisées.",
  "Can I use Rwandan francs?": "Puis-je utiliser les francs rwandais ?",
  "Yes. RWF is supported as the main working currency, and you can monitor additional currencies when your business needs them.": "Oui. Le RWF est pris en charge comme devise principale et vous pouvez suivre d’autres devises selon les besoins de votre entreprise.",
  "Are my documents kept together with my business data?": "Mes documents sont-ils conservés avec les données de mon entreprise ?",
  "Yes. Your Docs gives you a dedicated place for receipts, agreements, invoices, and other business files.": "Oui. Mes documents vous offre un espace dédié aux reçus, contrats, factures et autres fichiers professionnels.",
  "Can I access Kungahara on a phone?": "Puis-je accéder à Kungahara sur un téléphone ?",
  "Yes. The landing page and application are responsive, so you can use the core experience across desktop, tablet, and mobile screens.": "Oui. La page d’accueil et l’application s’adaptent aux ordinateurs, tablettes et téléphones.",
  "Let's build a clearer": "Construisons une entreprise",
  "business together.": "plus claire, ensemble.",
  "Have a question, need help getting started, or want to learn whether Kungahara fits your business? Send us a message.": "Vous avez une question, besoin d’aide pour commencer ou souhaitez savoir si Kungahara convient à votre entreprise ? Envoyez-nous un message.",
  "First name": "Prénom",
  "Last name": "Nom",
  "Email address": "Adresse e-mail",
  "Business name": "Nom de l’entreprise",
  "How can we help?": "Comment pouvons-nous vous aider ?",
  "Website": "Site web",
  "Enter your first name": "Saisissez votre prénom",
  "Enter your last name": "Saisissez votre nom",
  "Enter your business name": "Saisissez le nom de votre entreprise",
  "Tell us what you need": "Expliquez-nous votre besoin",
  "Send message": "Envoyer le message",
  "Sending…": "Envoi…",
  "Unable to send your message.": "Impossible d’envoyer votre message.",
  "Your message was sent to Kungahara support.": "Votre message a été envoyé à l’assistance Kungahara.",
  "One clear place to manage stock, sales, finances, and records, built for growing businesses.": "Un espace clair pour gérer le stock, les ventes, les finances et les dossiers, conçu pour les entreprises en croissance.",
  "Product": "Produit",
  "Get started": "Commencer",
  "Company": "Entreprise",
  "Contact": "Contact",
  "Legal": "Mentions légales",
  "Terms of service": "Conditions d’utilisation",
  "Privacy policy": "Politique de confidentialité",
  "Follow Kungahara": "Suivre Kungahara",
  "Product links": "Liens du produit",
  "Company links": "Liens de l’entreprise",
  "Legal links": "Liens juridiques",
  "Kungahara on GitHub": "Kungahara sur GitHub",
  "Email Kungahara": "Envoyer un e-mail à Kungahara",
  "© 2026 Kungahara. All rights reserved.": "© 2026 Kungahara. Tous droits réservés.",
  "Open navigation menu": "Ouvrir le menu de navigation",
  "Close navigation menu": "Fermer le menu de navigation",
  "Main navigation": "Navigation principale",
  "Language": "Langue",
};

export function landingText(value: string, language: LandingLanguage) {
  return language === "fr" ? french[value] ?? value : value;
}
